### ISSUE TITLE
Improve resource utilization on Compute nodes

### ISSUE THREAD

**Issue by Quentin-M** [stackanetes/stackanetes#140]
Stackanetes enables operators to run OpenStack as any other applications on top of Kubernetes. As such, OpenStack's services run alongside mixed workloads, potentially owned by various tenants. For fairness and in order to guarantee that the orchestrator's scheduler can make knowledgeable decisions, it is crucial to have the ability to arbitrarily define, reserve and limit OpenStack's resource utilization.

Kubernetes' [resource allocation model](http://kubernetes.io/docs/user-guide/compute-resources/) currently let operators define optional requests and limits for CPUs and Memory hardware resources. Different [Quality of Service policies](https://github.com/kubernetes/kubernetes/blob/master/docs/design/resource-qos.md) then define Kubernetes' behavior regarding to overcommitment and contention. Custom resource types can also be defined. Administrators may also define [quotas](http://kubernetes.io/docs/admin/resourcequota/walkthrough/) on a per-Namespace basis.

While defining resources' requests and limits for most of Stackanetes' applications is straight-forward following the documentation referenced above, and is a task left to end-users, there is currently one exception: Nova Compute, and more specifically, the _nova-libvirt_ pods. Running virtual machines are [arranged](https://libvirt.org/cgroups.html) on the hosts in different control groups than the libvirt and compute services that are executed by either rkt or Docker. Therefore, the resources that virtual machines consume are not accounted for by Kubernetes. This fact can easily be seen in the figure below, where the memory allocation of the virtual machine and containers are distinct and not summed whatsoever.

![systemd-cgtop](https://cloud.githubusercontent.com/assets/1332289/20485756/4c589cf6-affd-11e6-995c-0fb38d96e039.png)

Therefore, it is currently impossible to properly limit / monitor the resource usage of Nova Compute on Kubernetes. Virtual machines are able to get scheduled and started as long as the Kubernetes node has enough available physical memory ([Nova Compute's RamFilter](http://docs.openstack.org/newton/config-reference/compute/schedulers.html#RamFilter)). The desired behavior would be to have virtual machines scheduled until the pre-allocated memory for Nova Compute runs out.

The way I see it, there are mainly two parts to this issue. First, the resources used by the virtual machines must be accounted for in either the _nova-compute_ or _nova-libvirt_ containers for limiting / monitoring and helping the Kubernetes' scheduler to make good decisions. Second, the Nova Compute's scheduler should be aware that it doesn't have all the physical memory at its disposal but only what have been allocated.

Technically, on the Kubernetes side, we may be able to write a monitoring plugin that would sum the resource utilization of both the containers and virtual machines under the same metrics. And on the OpenStack side, we may either play with the `ram_allocation_ratio` / `cpu_allocation_ratio` or create a new filter for the scheduler. Note that ideally, the available resources reported by Nova should be correct.

**Comment by DTadrzak** [comment]
Why cannot we run nova-compute, nova-libvirt and three openvswitch processes as a single rkt-lkvm pod?

**Comment by Quentin-M** [comment]
@DTadrzak I am not familiar enough with the resource reporting when using the _lkvm_ stage1 isolation layer but I believe that it won't make a difference as resource requests/limits apply to containers (stage2) directly. Regardless, the VMs would still be registered to different scopes on systemd - which will be the _lkvm_'s systemd instead of the host's systemd - and their resources won't be accounted for. This idea also raises some fundamental issues. Off the top of my head, how could we run both Neutron/Open vSwitch/Nova services in the same pod while we have a clear separation (packages) between them? What about Docker users?

**Comment by Quentin-M** [comment]
In order to let OpenStack think that the only available memory is what we define as a container limit, defining a new libvirt driver based on the existing [libvirt.LibvirtDriver](https://github.com/openstack/nova/blob/master/nova/virt/libvirt/driver.py), and overwriting `get_available_resource` is enough. The hypervisor is properly reported with the proper amount of memory and this limit is updated as well when necessary. I also verified that the RamFilter indeed prevents launching new VMs past that limit.

The cleanest solution to have the VMs resource usage counted as part of the pod is to root the VMs' cgroup hierarchy under the pod's cgroup hierarchy. However, by default, a cgroup hierarchy is created per container, rather than per pod. This behavior doesn't respect our constraint of NOT having the VMs parented by the nova containers (e.g. an update should keep the VMs running). Since very recently, it is possible to have kubelet [layout](https://github.com/dubstack/kubernetes/blob/e425c6bbda08dfe4f963192e9aad3d581479411b/docs/proposals/pod-resource-management.md) cgroups differently and maintain a cgroup slice for each pod. 

**kubelet parameters**
```
  --cgroup-driver=systemd \
  --experimental-cgroups-per-qos \
  --cgroup-root=/
```

**tree sample**
```
  │   ├─BestEffort-pod17587970_fd3e_11e6_b240_0602d725b9dc.slice
│ │   │ ├─7889c4879721ff5a477b13d3ba75c750ad62f84ef994220d838a2e719d29035b
│ │   │ │ └─9541 /pause
│ │   │ └─d72c5c32d5ea4551d455ec6a6062b4603537f05df75bdd44e7b5195beec59f5a
│ │   │   ├─ 9638 /nginx-ingress-controller --nginx-configmap=tectonic-system/tectonic-custom-error --default-backend-service=tectonic-system/default-http-backend --default-ssl-certificate=tectonic-system/tectoni
│ │   │   ├─ 9681 nginx: master process nginx
│ │   │   ├─11050 nginx: worker process is shutting down
│ │   │   ├─11051 nginx: worker process is shutting down
│ │   │   ├─11052 nginx: worker process is shutting down
│ │   │   ├─11053 nginx: worker process is shutting down
│ │   │   ├─11559 nginx: worker process
│ │   │   ├─11560 nginx: worker process
│ │   │   ├─11561 nginx: worker process
│ │   │   └─11562 nginx: worker process
```

This would allow us to specify the root slice of the VM's cgroups as the pod slice with libvirt, using the XML `domain/resource/partition` [configuration](https://libvirt.org/cgroups.html#customPartiton). Also, libvirt [hardcodes](https://github.com/libvirt/libvirt/blob/381b9d0b0acc32c57e5f3e13b5ff1e19667cefbd/src/util/virsystemd.c#L117) the `.slice` suffix but as shown above, kubelet create pod slices with the suffix too. 

I will know try to see how Nova could be modified to inject this custom cgroup slice and verify it works.

**Comment by Quentin-M** [comment]
Here's what we want:
- Terminating a Nova pod does not terminate the VMs
  - Already achieved by the usage of the `preStop`/`postStart` hooks 
- Scheduling a new VM that would exceed the set limit is not possible
  - Achieved by adding memory requests and by tweaking `get_available_resource`
- The memory usage that is reported for the Nova pod contains both the memory used by `nova-compute` and the VMs so that:
  - Ops have a better vision of how much Nova consumes
  - Kubernetes can take smart decisions when it comes to reclaiming memory or killing Nova for exceeding its memory limit

The memory consumption of a pod is calculated as the sum of the the memory consumption of the containers that are part of it. This will be true until Kubernetes decides to create pod cgroups by default and to change cAdvisor to monitor that instead (which might never happen). This means that the VMs' processes must be parented under the nova-compute container's memory cgroup is we want their memory to be accounted for.

Since we can't assign the VMs directly to the desired cgroup, we have to re-assign them asynchronously. Fortunately, this is quite straight-forward to do on GNU/Linux. We could have the driver do it for us (if there is a right place to do so), or have a separate process managing that. Additionally, when a process leader is migrated from one memory cgroup to another, and when the destination cgroup has `memory.move_charge_at_immigrate = 0b11`, all anonymous pages and file pages of that process are moved to it too. In other words, the memory utilization of the migrated process is accounted on its new cgroup, which is what we need. See https://www.kernel.org/doc/Documentation/cgroup-v1/memory.txt.

The issue with having the VMs under the nova-compute's cgroup is that terminating that container will orphan the VMs and kill them too. However, we currently have a hook that is executed right before the container is being stopped. This hook migrates the VMs when the pod is stopped and the node is Unschedulable. We could have it to re-parent the VMs back to the `/machine.slice` cgroup when the pod is stopped and the node is still Schedulable so that the VMs don't get terminated early. Since we have a symmetric hook that is executed after the pod is started, we could re-attach the VMs to the pod. 

It would solve the third point above. However, here is the catch. When the nova-compute's pod is being stopped, it might be for two reasons:
- Because of an update, in which case we want the VMs to keep running on the host and therefore their processes to be re-parented on the host
- Because Kubernetes has decided to kill it for reclaim memory or because it has taken too much memory, in which case we should migrate the VMs out if possible - or kill them
Unfortunately, there is no way to distinguish between the two cases and can only pick one of the two behaviors. The first one describes what we have been wanting to do until now (otherwise we'd simply have attached the VMs under the nova-libvirt container and called it a day), the second one fits better our use-case of co-locating workloads and the general use-case anyways where there are multiple hosts available to take the VMs load.

Does the implementation sound reasonable? 
Which behavior do you prefer?

/cc @DTadrzak @PiotrProkop
