### ISSUE TITLE
eliminate host based hacks

### ISSUE THREAD

**Issue by polvi** [stackanetes/stackanetes#16]
Currently an admin must login to the machine to create `/var/lib/nova` `/var/lib/libvirt` and `/home/core/resolv.conf`. We need to figure out how we are going to kill this. It might be most reasonable to approach this once we have nova-compute in the state we want it in.

**Comment by ss7pro** [comment]
K8S 1.3 will have init containers, which can resolve this issue.

**Comment by DTadrzak** [comment]
I think that issue is covered by #9 and #10

**Comment by DTadrzak** [comment]
Problem solved
