### ISSUE TITLE
 sudo -E pip install -r requirements.txt error

### ISSUE THREAD

**Issue by 1106944911** [stackanetes/stackanetes#22]
HI ，want to use stackanetes on ubuntu 15.04 viv OS。 It occur to errors, when exec  sudo -E pip install -r requirements.txt , anyone help me ?

building 'netifaces' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -DNETIFACES_VERSION=0.10.4 -DHAVE_GETIFADDRS=1 -DHAVE_GETNAMEINFO=1 -DHAVE_NETASH_ASH_H=1 -DHAVE_NETATALK_AT_H=1 -DHAVE_NETAX25_AX25_H=1 -DHAVE_NETECONET_EC_H=1 -DHAVE_NETIPX_IPX_H=1 -DHAVE_NETPACKET_PACKET_H=1 -DHAVE_LINUX_IRDA_H=1 -DHAVE_LINUX_ATM_H=1 -DHAVE_LINUX_LLC_H=1 -DHAVE_LINUX_TIPC_H=1 -DHAVE_LINUX_DN_H=1 -DHAVE_SOCKADDR_AT=1 -DHAVE_SOCKADDR_AX25=1 -DHAVE_SOCKADDR_IN=1 -DHAVE_SOCKADDR_IN6=1 -DHAVE_SOCKADDR_IPX=1 -DHAVE_SOCKADDR_UN=1 -DHAVE_SOCKADDR_ASH=1 -DHAVE_SOCKADDR_EC=1 -DHAVE_SOCKADDR_LL=1 -DHAVE_SOCKADDR_ATMPVC=1 -DHAVE_SOCKADDR_ATMSVC=1 -DHAVE_SOCKADDR_DN=1 -DHAVE_SOCKADDR_IRDA=1 -DHAVE_SOCKADDR_LLC=1 -DHAVE_PF_NETLINK=1 -I/usr/include/python2.7 -c netifaces.c -o build/temp.linux-x86_64-2.7/netifaces.o
    netifaces.c:1:20: fatal error: Python.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-3b9N7X/netifaces/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-493H9p-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-3b9N7X/netifaces/

**Comment by PiotrProkop** [comment]
assigning @DTadrzak

**Comment by DTadrzak** [comment]
Install following packages: 

- python-dev
- python-netifaces

**Comment by v1k0d3n** [comment]
@DTadrzak i suggested in #16 a container that could take care of the deployment. do you have any thoughts or opinions on this? I would imagine that _most_ deployment hosts would have docker or that users would have access to a docker host that could be leveraged. this could be a good control point for smooth deployments with less issues.

**Comment by PiotrProkop** [comment]
This [pull request](https://github.com/stackanetes/stackanetes/pull/20) tries to address this issue but it is still WIP.

**Comment by v1k0d3n** [comment]
@PiotrProkop i missed it! perfect :)

**Comment by 1106944911** [comment]
thank you, the problem have been  solved ， but have another errors,maybe becaused by my network environment @DTadrzak

**Comment by 1106944911** [comment]
python setup.py build && python setup.py install --cert ~/proxy.crt  @DTadrzak 
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 246, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/usr/local/lib/python2.7/dist-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/usr/local/lib/python2.7/dist-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/usr/local/lib/python2.7/dist-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/usr/local/lib/python2.7/dist-packages/pbr/packaging.py", line 710, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /home/ubuntudev/project/stackanetes-master/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?

**Comment by DTadrzak** [comment]
Can you try to run stackanetes in Docker? 
docker run --net=host -it ubuntu bash

**Comment by 1106944911** [comment]
Okay ，thank you

**Comment by DTadrzak** [comment]
I'm glad it helped.
