### ISSUE TITLE
Machine requirements ?

### ISSUE THREAD

**Issue by ant31** [stackanetes/stackanetes#25]
> Kubernetes 1.2 cluster with minimum 3 kubernetes minions/workers

Is it possible to document minimum memory / cpu per node too?

**Comment by alekssaul** [comment]
Hi @ant31 ,

I don't think we've done testing around resource requirements. As a general idea; in my lab, node with persistent-control label set to ~16 GB ram, node with non-persistent-control label set to ~ 64 GB and compute node is set to ~ 72 GB ram.
