### ISSUE TITLE
Mono-node and labels

### ISSUE THREAD

**Issue by ant31** [stackanetes/stackanetes#28]
I'm trying to reduce requirements to deploy stackanetes for dev env. 

To deploy everything on a single node, I propose a different labeling:
instead of  using a label `app=xxxx`, we can use `xxxx=yes`

It's still possible to deploy on 3-nodes:
```bash
kubectl label node minion1 persistent-control=yes
kubectl label node minion2 non-persistent-control=yes
kubectl label node minion3 compute=yes
```

But also on 1 node:
```bash
kubectl label node minion1 persistent-control=yes non-persistent-control=yes compute=yes
```

**Comment by DTadrzak** [comment]
I agree. We have to change the manner of node labeling. 

BTW, currently we cannot run network-node and compute-node one the same node.

**Comment by ant31** [comment]
I don't know to much about openstack itself, can you quickly explain why ? 

Do you think there is a way to make them happy together?

**Comment by DTadrzak** [comment]
Because both pods are running with flag (net=host) and consist of openvswitch components. You cannot have two instances of openvswitch services on same node. We are working to solve that problem. 
But you are able to run all in one (without network-node) which allow you to deploy VM.

**Comment by Quentin-M** [comment]
That's fixed in newer versions, as documented in the README, with the usage of `openstack-control-plane=enabled` and `openstack-compute-node=enabled`
