### ISSUE TITLE
remove zookeeper dependency

### ISSUE THREAD

**Issue by philips** [stackanetes/stackanetes#4]
zookeeper is used internally as a sort of workflow controller for when services start and to fetch configuration. This is a carry over from the kolla project that developed the containerized images of the OpenStack components.

Nearly all of this can be replaced by Kubernetes [ConfigMaps](http://kubernetes.io/docs/user-guide/configmap/) or Kubernetes [Secrets](http://kubernetes.io/docs/user-guide/secrets/).

**Comment by Quentin-M** [comment]
Solved.
