### ISSUE TITLE
Open Source Readiness

### ISSUE THREAD

**Issue by philips** [stackanetes/stackanetes#5]
In order to make this repo open source we need to do a number of fundamental things:

- [x] Document all known issues as GitHub issues
- [x] Move things we know we want to fix immediately as P0 and add to v0.1.0 milestone
- [x] Write a README that accomplishes the following:
  - [x] Introduces the project with diagrams/videos
  - [x] Describes the necessary configuration of Kubernetes
  - [x] Provides simple 5 minute getting started guide
  - [ ] Talks through contribution process

**Comment by dims** [comment]
@philips @DTadrzak @PiotrProkop @polvi : Looks like Kolla-Kubernetes is making good progress (https://review.openstack.org/#/q/project:^openstack/kolla-kubernetes). Is the intention of this project going to be a parallel project?

**Comment by Quentin-M** [comment]
Referencing spec PR: https://review.openstack.org/#/c/304182/
