### ISSUE TITLE
Images fail to start

### ISSUE THREAD

**Issue by SaMnCo** [stackanetes/stackanetes#56]
Hi there, 

Not sure it is related to Stackanates or to Kolla, but I always have this issue when the pod start: 

```
$ kubectl logs mariadb-218087206-hshxq
INFO:__main__:Kolla config strategy set to: None
INFO:__main__:Loading config file at /var/lib/kolla/config_files/config.json
Traceback (most recent call last):
  File "/usr/local/bin/kolla_set_configs", line 263, in <module>
    sys.exit(main())
  File "/usr/local/bin/kolla_set_configs", line 258, in main
    execute_config_strategy()
  File "/usr/local/bin/kolla_set_configs", line 193, in execute_config_strategy
    config = load_config()
  File "/usr/local/bin/kolla_set_configs", line 166, in load_config
    config = load_from_file()
  File "/usr/local/bin/kolla_set_configs", line 154, in load_from_file
    with open(config_file) as f:
IOError: [Errno 2] No such file or directory: '/var/lib/kolla/config_files/config.json'
```

This happens with both my custom Ubuntu images, but also with the Stackanetes images on quay.io. Did anyone get the same issue? 
I deploy to a 1.2.4 k8s cluster, on CoreOS, with 2 minions (Intel NUC, 32GB RAM, 4 cores)

My ideas about the issue: 
* I see the docker entrypoint in the readme, but I have no idea how to use it. Are there any guidelines to use that? 
* There is a "context" file in the stackanetes.conf, and I don't understand its role. 

Any guidance appreciated,
Many thanks in advance, 
Best,

**Comment by ss7pro** [comment]
@PiotrProkop @DTadrzak

**Comment by Quentin-M** [comment]
Hi,

Could you please give it a try with the latest deployer? Check the new README to learn more about the process. By default, the images that it will use are `quay.io/stackanetes/stackanetes-%s:barcelona`.
